# Generated by Django 3.0.2 on 2020-08-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brahyaty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brahyaty.Subs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('contrats_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brahyaty.Contrats')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brahyaty.Sub_detail')),
            ],
        ),
    ]
