# Generated by Django 3.0.2 on 2020-08-07 03:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nutritions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodid', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('nutrients', jsonfield.fields.JSONField(default=dict)),
                ('category', models.CharField(max_length=200)),
                ('categoryLabel', models.CharField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
    ]
